on: 
  push:
    branches:
      - master
name: Deploy to AWS Lambda 
jobs:
  deploy:
    name: deploy
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          mkdir vendor
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t vendor
      - name: Create zip
        run: zip -r bitmex-tools.zip *.py $VENDOR_DIR
